config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :collections do
    member do
      post :parse
    end
  end
  root "collections#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :manifests, dependent: :destroy
  validates :manifest_url, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :manifest
end

app/models/manifest.rb
class Manifest < ApplicationRecord
  belongs_to :collection
  has_many :images, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update parse destroy ]
  before_action :authenticate_user!, except: %i[ show ]

  # GET /collections or /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1 or /collections/1.json
  def show
    @image_size = parse_image_size(params[:size])
    @smaller_size = @image_size / 2
    @larger_size = @image_size * 2
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /collections/1/parse
  def parse
    CollectionParserJob.perform_later(@collection.manifest_url)
    respond_to do |format|
      format.html { redirect_to collection_url(@collection), notice: "Background job to parse manifest has been queued." }
      format.json { render :show, status: :ok, location: @collection }
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:manifest_url, :html_url, :label)
    end

    # parse image size
    def parse_image_size(size_str)
      size_param = size_str.to_i
      size_param > 0 ? size_param : 128
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
  def iiif_image_tag base_url, size
    image_tag "#{base_url}/full/#{size},/0/default.jpg"
  end
end

app/views/collections/_form.html.erb
<%= form_with(model: collection) do |form| %>
  <% if collection.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :manifest_url, style: "display: block" %>
    <%= form.text_field :manifest_url %>
  </div>

  <div>
    <%= form.label :html_url, style: "display: block" %>
    <%= form.text_field :html_url %>
  </div>

  <div>
    <%= form.label :label, style: "display: block" %>
    <%= form.text_field :label %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Show this collection", @collection %> |
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/index.html.erb
<h1>Collections</h1>

<ul id="collections">
  <% @collections.each do |collection| %>
    <li><%= link_to collection.label, collection %></li>
  <% end %>
</div>

<p><%= button_to "New collection", new_collection_path, method: :get %></p>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/show.html.erb
<h1>
  <%= link_to "Collections", collections_path %>:
  <%= @collection.label %>
  <%= link_to "-", collection_path(@collection, size: @smaller_size), class: "btn" %>
  <%= link_to "+", collection_path(@collection, size: @larger_size), class: "btn" %>
  <%= link_to "Edit", edit_collection_path(@collection), class: "btn" %>
</h1>

<div class="container">
<% @collection.manifests.each do |manifest| %>
  <div class="manifest">
    <h2>
      <%= manifest.label %>
      <%= link_to "IIIF", manifest.manifest_url, class: "btn" %>
      <%= link_to "HTML", manifest.html_url, class: "btn" %>
    </h2>
    <% manifest.images.each do |img| %>
      <%= iiif_image_tag img.image_url, @image_size %>
    <% end %>
    <% if manifest.images.size == 0 %>
      <p>No Images Found</p>
    <% end %>
  </div>
<% end %>
</div>

<% if user_signed_in? %>
<p>
  Collection Actions:
  <%= button_to "Parse", parse_collection_path(@collection), method: :post, class: "btn" %>
  <%= button_to "Delete", @collection, method: :delete, class: "btn" %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="navbar">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to "Logout", destroy_user_session_path, class: "btn" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "btn" %>
      <% end %>
    </p>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>